### ISSUE TITLE
Overload datalist 

### ISSUE THREAD

**Issue by parkhabit** [fac-12/TJAB-AutoComplete#28]
When typing in only one letter the resulting datalist becomes so large it slows down the site and nearly crashes. The spinning circle of death appears. 
![screen shot 2017-11-17 at 10 04 29](https://user-images.githubusercontent.com/16639540/32942267-6e3ca354-cb80-11e7-8c2d-232eda59d9a8.png)

**Comment by sophielevens** [comment]
Also there is a bit of a flicker in the autocomplete list when it appears.
![buffy](https://user-images.githubusercontent.com/25961258/32942566-576760d2-cb81-11e7-8524-1a7bff0ec5d3.gif)

**Comment by Johanna-hub** [comment]
Thanks @parkhabit and @sophielevens we're now only returning characters with that letter as first letter, a lot faster now!
