### ISSUE TITLE
In the search.js if you are to search with a regex instead of a string

### ISSUE THREAD

**Issue by Dragomirc** [fac-12/TJAB-AutoComplete#37]

**Comment by Dragomirc** [comment]
you might not have to wright names array function, which would probably make the website faster as you won't have to make the whole database lowercase for every input. I might be wrong)

**Comment by eliasmalik** [comment]
I was about to write this issue myself. You can perform case-insensitive searches with regex using the `/i` flag. 

This will also mean you don't need to re-capitalise the search results after having found them.

**Comment by Johanna-hub** [comment]
Thanks a lot @Dragomirc and @eliascodes, that's all done now and I've also done regex so it only matches at the beginning so we're only getting characters whose name start with character.  A  lot faster now!
