### ISSUE TITLE
Sending API response as plain/text

### ISSUE THREAD

**Issue by eliasmalik** [fac-12/TJAB-AutoComplete#38]
In your endpoint handler, you are sending your response back as a forward-slash delimited string with a `plain/text` content type:
https://github.com/fac-12/TJAB-AutoComplete/blob/030ddbed3d1dd4cabee08698f568c29b5c5e0d20/src/handlers.js#L40-L46

On the front-end you then split the response text on the delimiter and proceed to use the array. I'd be interested to know why you chose this instead of using JSON to send the array back.

In general I would recommend using (stringified) JSON as the response format because it is a well-specified, widely used standard, and any potential performance difference will be trivial. In particular, if you're ever creating an API that has to be consumed by the public or other developers, requiring them to write custom parsing logic to process your response (even if it's just one line) is an unnecessary burden.

**Comment by Johanna-hub** [comment]
Thanks @eliascodes, I've done that and learnt all about query string!
