### ISSUE TITLE
filter instead of for loop

### ISSUE THREAD

**Issue by eliasmalik** [fac-12/TJAB-AutoComplete#39]
In your wordSearch function:
https://github.com/fac-12/TJAB-AutoComplete/blob/030ddbed3d1dd4cabee08698f568c29b5c5e0d20/src/search.js#L19-L24

You are constructing a new array conditionally from the elements of an existing array. This is the precise use-case for `filter`, which (IMO) is more readable.

**Comment by Johanna-hub** [comment]
Thanks a lot!  That makes sense!
